### ISSUE TITLE
[BUG] Walia seems to be missing from the latest update.

### ISSUE THREAD

**Issue by midnight4sale** [AMPZNetwork/Colony-Lost-In-Deep-Space#2]
**Describe the bug**
Walia seems to be missing from the latest update. The game gets to screen below and won't start.

**To Reproduce**
1. Start pack

**Expected behavior**
Game starts.

**Crash Log**
[2021-09-09-2.log.gz](https://github.com/AMPZNetwork/Colony-Lost-In-Deep-Space/files/7140800/2021-09-09-2.log.gz)

**Screenshots**
![Screenshot of Game Start](https://user-images.githubusercontent.com/18190403/132788274-08ee75f4-7115-4918-bf98-ef50fc8b0be8.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - Colony: Lost in Deep Space Version 2.1
 - Platform: Curseforge
 - Extra mods added by you: None

**Comment by LabsZero** [comment]
Thank you for the report, the issue has been resolved.
