### ISSUE TITLE
[Colony] [2.3] Extra Planet's planet and moon names bug.

### ISSUE THREAD

**Issue by Arkron** [AMPZNetwork/Colony-Lost-In-Deep-Space#3]
**Description of the bug:**
The "Extra Planets" mod's planets and moons are shown with unedited names.

**To Reproduce**
1. Build/spawn the Planet Progression mod's telescope, and both research papers for planets such as: Jupiter, Neptune, Uranus, Saturn and moons such as: Deimos, Phobos, Titan, Europa.
2. Put a battery in the telescope, and use it to research all the papers.
3. Check your Galaxy Map for the names of the Extra Planets mod's planets and moons.

**Expected behavior**
The planets for Extra Planets up until the modpack's version of 2.1 were shown as "2.0

**Screenshots**
How the names for the Extra Planets mod's planets are displayed as of the 2.3 version of the modpack: https://i.imgur.com/I55QKTa.png

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro
 - Colony: Lost in Deep Space Version 2.3
 - Extra mods added by you: none

**Comment by LabsZero** [comment]
Should be resolved in 2.3.2 or higher.
